steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cicd-repo/app:$SHORT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cicd-repo/app:$SHORT_SHA'

images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/cicd-repo/app:$SHORT_SHA'
